name: ati2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  google_fonts: ^6.2.1
  camera: ^0.11.3
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0
  path_provider: ^2.1.2
  path: ^1.9.0
  sqflite: ^2.3.2
  tflite_flutter: ^0.12.1
  image: ^4.1.7
  intl: ^0.20.2
  provider: ^6.1.2
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter:

  uses-material-design: true

  assets:
    - assets/mobile_face_net.tflite
    - assets/bg_light.png
    - assets/bg_dark.png
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
